channels:
- conda-forge
dependencies:
- python=3.9.7
- pip
- pip:
  - mlflow
  - cffi==1.15.0
  - cloudpickle==2.0.0
  - defusedxml==0.7.1
  - lightgbm==3.3.2
  - matplotlib==3.5.1
  - psutil==5.9.0
  - scikit-learn==1.0.2
name: mlflow-env
